### ISSUE TITLE
Headings needs space under when above images

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#588] opened 2019-12-08 16:07 UTC
cc: @jeanservaas can you help provide the correct spec.

https://gatsby-theme-carbon.now.sh/components/Grid
<img width="523" alt="Screen Shot 2019-12-08 at 8 01 58 AM" src="https://user-images.githubusercontent.com/32881239/70392140-6e515e00-1991-11ea-9719-b667a029b34b.png">

https://www.ibm.com/brand/advertising
<img width="645" alt="Screen Shot 2019-12-05 at 4 22 29 PM" src="https://user-images.githubusercontent.com/32881239/70392155-8e811d00-1991-11ea-9e32-d82f19dfa6b8.png">

<img width="614" alt="Screen Shot 2019-12-05 at 4 22 25 PM" src="https://user-images.githubusercontent.com/32881239/70392156-93de6780-1991-11ea-80af-1c985fa0203e.png">

**Comment by vpicone** [comment] 2019-12-16 19:18
@mjabbink brand is applying a custom style here that is overriding our margin. removing that rule adds the appropriate space:
![Screen Shot 2019-12-16 at 1 17 40 PM](https://user-images.githubusercontent.com/4078018/70935732-7a2ec700-2006-11ea-9713-a94eef0bb677.png)

**Comment by vpicone** [comment] 2019-12-16 19:37
the h4 problem is unrelated and duplicate of #591 gonna close this and open an issue for brand to fix their override.

**Closed by vpicone** 2019-12-16 19:37 UTC
Labels: priority: high

**Comment by mjabbink** [comment] 2019-12-16 20:12
I need to move this to Brand Center issues
