### ISSUE TITLE
Bug: switcher and search icons

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#83] opened 2019-05-20 19:42 UTC
if scrolling fast they disappear but hover is still there.  Check screen video.

[Screen Recording 2019-05-20 at 3.34.17 PM.zip](https://github.com/carbon-design-system/gatsby-theme-carbon/files/3199539/Screen.Recording.2019-05-20.at.3.34.17.PM.zip)

Seems fine in Chrome

**Comment by vpicone** [comment] 2019-05-22 16:11
@mjabbink I'm not able to reproduce this on the current build, It might have been fixed with a recent update. Can you try again at https://gatsby-theme-carbon.now.sh/?

**Comment by alisonjoseph** [comment] 2019-06-10 17:55
Not seeing this anymore with latest version, feel free to re-open if we missed something.

**Closed by alisonjoseph** 2019-06-10 17:55 UTC
Labels: status: needs more info 🤷‍♀️
