### ISSUE TITLE
Card addition

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#82] opened 2019-05-20 18:46 UTC
@vpicone @alisonjoseph 
Need to add bottom right type size to "Article cards"

![Screen Shot 2019-05-20 at 2 05 24 PM](https://user-images.githubusercontent.com/32881239/58044318-74731080-7b0d-11e9-8893-c77f7d33cc9d.png)

These cards should all be larger type
https://ibmbrandcenter-preview.mybluemix.net/expression

It’s like the one used here:
https://www.ibm.com/design/practices/

I almost thing we need every header sample you did in "Resource card" also in use for "Article cards"

**Comment by alisonjoseph** [comment] 2019-05-20 18:58
@jeanservaas @mjabbink 

What should the type tokens be for the two font sizes? Right now they are `heading-01` w/ font weight 400 for the smaller heading and `productive-heading-03` for the larger.

The Carbon site currently uses `heading-01` (with the font weight set to 400), so that's where that option came from. 
https://www.carbondesignsystem.com/resources/

**Comment by vpicone** [comment] 2019-12-09 20:11
duplicate of #139

**Closed by vpicone** 2019-12-09 20:11 UTC
Labels: status: needs more info 🤷‍♀️, type: dev :robot:
