### ISSUE TITLE
Larger header in Feature, Article and image cards too small. See Carbon and DL sites landing pages

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#139] opened 2019-06-03 20:19 UTC
@vpicone @alisonjoseph Can we add Jeannie to this repo?

Not sure what happened. The ArticleCard was correct but just needed the larger size added but you removed the other size that was there. We needed that size as well. Two types. One with smaller size like in Carbon Articles and one with bigger (with and without labels). Both are correct and used here: https://www.carbondesignsystem.com/

https://gatsby-theme-carbon.now.sh/components/ImageCard

https://gatsby-theme-carbon.now.sh/components/ArticleCard

https://gatsby-theme-carbon.now.sh/components/ImageCard

Expected:
https://www.carbondesignsystem.com/

https://www.ibm.com/design/language/

**Comment by mjabbink** [comment] 2019-06-03 20:43
aha, I think I know the issue. DL and Carb have that size that is fluid so in XL breakpoint is goes up to next size. I think that is the issue

**Comment by vpicone** [comment] 2019-06-03 21:13
@mjabbink having trouble inferring what the problem is, could throw together an illustration by chance?

**Comment by jeanservaas** [comment] 2019-06-03 21:38
@vpicone and I just had a chat about this ish -- I just want to make sure I'm understanding it correctly.

At first, I didn't think we ever used 16pt type (i.e. $body-short-02) in article cards, just image and feature cards... but then, it does seem like / design uses both 14 and 16pt in their article cards.

![image](https://user-images.githubusercontent.com/43144260/58835533-d8bcc680-861b-11e9-8fee-aedc891441ad.png)

<br>

Here are some article cards in the wild ... on /design and Carbon... 

<br>

**Carbon: 14pt / 12pt**

![image](https://user-images.githubusercontent.com/43144260/58835734-57196880-861c-11e9-901a-17241c7d100d.png)

<br>

**/design: 14pt / 12pt**
![image](https://user-images.githubusercontent.com/43144260/58836037-31d92a00-861d-11e9-9c0e-0e7097f32b13.png)

<br>

**/design: 16pt**
![image](https://user-images.githubusercontent.com/43144260/58836182-add37200-861d-11e9-8873-e648de10dbdd.png)


---------------

I guess I would just be careful of this example because I don't think we ever recommend using a 12, 14 and 16pt type together in an article card.

![image](https://user-images.githubusercontent.com/43144260/58836244-e1ae9780-861d-11e9-8ccc-b8dbe5361b90.png)

**Comment by mjabbink** [comment] 2019-06-03 22:06
the current Carb site on home page has it right I think. Some cards have smaller heading type and the ones that are Feature cards or leading Article cards have the additional label with 20—24 (fluid only to LG —XL) which is a nice scale for those lead article cards. We need both I think.

**Comment by mjabbink** [comment] 2019-06-03 23:03
<img width="921" alt="Screen Shot 2019-06-03 at 7 02 49 PM" src="https://user-images.githubusercontent.com/32881239/58840073-4f64be80-8632-11e9-8060-0e9442ba4e83.png">

**Comment by mjabbink** [comment] 2019-06-03 23:07
this compares DL with Design for AI site 


<img width="1228" alt="Screen Shot 2019-06-03 at 7 06 38 PM" src="https://user-images.githubusercontent.com/32881239/58840220-c437f880-8632-11e9-8b4e-c7e71f6fc7fd.png">

**Comment by mjabbink** [comment] 2019-06-03 23:28
This comparison might help visualize better. Look at the type on the large hover on top of lead video. 

http://ai-design.mybluemix.net/design/ai/

https://www.ibm.com/design/language/

If you scale browser from XL to LG in DL site you’ll see that type scale down. Hope this helps rather than confuse.

**Comment by alisonjoseph** [comment] 2019-06-05 15:12
I think I'm still slightly confused on what the correct type tokens should be for the article card. 

This is what we currently have in the theme

`productive-heading-03` title
`heading-01` subtitle
`caption-01` author, date, read time

@jeanservaas @mjabbink if you could just let us know what those 3 type tokens should be instead we can make the update.

**Comment by mjabbink** [comment] 2019-06-06 02:40
@jeanservaas correct if I’m wrong but the header 03 I’m looking for is expressive and would jump to 24px in XL breakpoints. Currently it’s set up as Productive H3 which maintains 20px between LG and XL breakpoints. Current DL and Carb use the Expressive I think and Gatsby theme Productive.

**Comment by alisonjoseph** [comment] 2019-12-13 15:46
I think we can close this, and open a new issue w/ specific spec if things need to change

**Closed by alisonjoseph** 2019-12-13 15:46 UTC
Labels: status: waiting for response :thought_balloon:, type: bug 🐛
